"""S1-owned: claim-graph schema freeze (S4 shape, docs/adr/0003).

The golden JSONs under tests/golden/claim_graph/ were generated by running S4's REAL
builder + exporter (origin/session/4-engine, commit 3931c38) over the frozen mocks.
If these ever stop validating, the exporter and the frozen contract diverged.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

import pytest

from semlock.ir.serialize import _validate, load_schema  # noqa: PLC2701

GOLDEN_DIR = Path(__file__).parent / "golden" / "claim_graph"
GRAPH_SCHEMAS = ("ir.schema.json", "claim-graph.schema.json")


def load_graph_schema() -> dict[str, Any]:
    path = Path(__file__).resolve().parents[1] / "schema" / "claim-graph.schema.json"
    with path.open("r", encoding="utf-8") as fh:
        loaded: Any = json.load(fh)
    return cast("dict[str, Any]", loaded)


def validate_text(text: str) -> list[str]:
    payload: Any = json.loads(text)
    schema = load_graph_schema()
    return _validate(payload, schema, schema, "$")


@pytest.mark.parametrize(
    "golden", sorted(p.name for p in GOLDEN_DIR.glob("*.json"))
)
def test_golden_exports_validate(golden: str) -> None:
    text = (GOLDEN_DIR / golden).read_text(encoding="utf-8")
    assert validate_text(text) == []


def test_goldens_are_byte_deterministic_artifacts() -> None:
    """Trailing newline, 2-space indent, no CR — the INV-1 export contract."""
    for path in sorted(GOLDEN_DIR.glob("*.json")):
        text = path.read_text(encoding="utf-8")
        assert text.endswith("}\n"), path.name
        assert "\r" not in text, path.name
        assert '\n  "format_version"' in text, path.name


def test_wire_versions_frozen() -> None:
    for path in sorted(GOLDEN_DIR.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        assert payload["format_version"] == "0.1.0"  # claim-graph wire format
        assert payload["ir_format_version"] == "0.2.0"  # IR freeze


def test_rejects_wrong_claim_graph_version() -> None:
    text = (GOLDEN_DIR / "clean_merge_new_method__a.json").read_text(encoding="utf-8")
    bad = text.replace('"format_version": "0.1.0"', '"format_version": "9.9.9"', 1)
    assert _validate(json.loads(bad), load_graph_schema(), load_graph_schema(), "$")


def test_rejects_unknown_property() -> None:
    payload = json.loads(
        (GOLDEN_DIR / "clean_merge_new_method__a.json").read_text(encoding="utf-8")
    )
    payload["extra"] = 1
    schema = load_graph_schema()
    assert _validate(payload, schema, schema, "$")


def test_resolved_edge_requires_target() -> None:
    payload = json.loads(
        (GOLDEN_DIR / "removed_export_function_deleted__b.json").read_text(
            encoding="utf-8"
        )
    )
    edge = next(
        e
        for e in payload["depends_on"]
        if e["status"] == "resolved" and e["target_id"] == "pkg.models::User"
    )
    edge["target_id"] = None
    errors = _validate(payload, load_graph_schema(), load_graph_schema(), "$")
    assert any("target_id" in e for e in errors)


def test_node_id_grammar_enforced() -> None:
    text = (GOLDEN_DIR / "clean_merge_new_method__a.json").read_text(encoding="utf-8")
    payload = json.loads(text)
    payload["nodes"][0]["id"] = "pkg.app.welcome"  # dotted: no :: separator
    schema = load_graph_schema()
    assert _validate(payload, schema, schema, "$")


@pytest.mark.parametrize("def_name", ["span", "param", "signature", "member"])
def test_shared_defs_match_ir_schema(def_name: str) -> None:
    """The claim-graph schema re-declares IR $defs; divergence is a contract bug."""
    ir = load_schema()
    graph = load_graph_schema()
    assert graph["$defs"][def_name] == ir["$defs"][def_name]


def test_schema_files_present_and_registered() -> None:
    schema_dir = Path(__file__).resolve().parents[1] / "schema"
    for name in GRAPH_SCHEMAS:
        assert (schema_dir / name).is_file()
